# Generated by Django 5.1.7 on 2025-03-14 16:51

import django.db.models.deletion
import imagehub.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image_count', models.PositiveIntegerField(default=0, editable=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('image_file', models.ImageField(upload_to=imagehub.models.upload_to_path)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('width', models.PositiveIntegerField(editable=False)),
                ('height', models.PositiveIntegerField(editable=False)),
                ('file_size', models.PositiveIntegerField(editable=False)),
                ('is_color', models.BooleanField(editable=False)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_set', to='imagehub.folder')),
            ],
            options={
                'ordering': ['-upload_date'],
                'constraints': [models.UniqueConstraint(fields=('folder', 'slug'), name='unique_folder_slug')],
            },
        ),
    ]
